[env]
CLUSTER_NAME = "demo-kube"
DOCKER_BUILDKIT = "1"
# BP_RUST_TOOLCHAIN = "1.86"
# KIND_EXPERIMENTAL_PROVIDER = "podman" # to use podman and podman-docker

[tools]
# docker (or podman + some config) should be available for some of thoses tools
# helm = '3.12'
kubectl = '1.24'
# helmfile = '0.155'
kind = '0.20'
rust = '1.86'

[tasks.k8s_create_kind]
description = "Create kind cluster with metrics-server and run kubectl-view-allocations"
run = """
# k3d cluster create "$CLUSTER_NAME" --agents 2
sudo systemctl start docker
kind create cluster --name "$CLUSTER_NAME"
kubectl cluster-info --context kind-"$CLUSTER_NAME"
kubectl apply -f tests/metrics-server-components.yaml
sleep 5
kubectl top node
cargo run
"""

[tasks.k8s_delete_kind]
description = "Delete kind cluster"
run = """
# k3d cluster delete "$CLUSTER_NAME"
kind delete cluster --name "$CLUSTER_NAME"
"""

[tasks.k8s_create_kwok]
description = "Create KWOK cluster with test pods and run kubectl-view-allocations"
run = """
# echo "require docker, with podman I got timeout on my machine"
kwokctl create cluster --name="$CLUSTER_NAME"
kwokctl get clusters
kubectl cluster-info --context kwok-"$CLUSTER_NAME"
kwokctl scale node --replicas 2 --name="$CLUSTER_NAME"
kubectl get node
kubectl create deployment pod --image=pod --replicas=5
kubectl get pods -o wide
echo "use '--accept-invalid-certs' with kube view-allocations"
cargo run -- --accept-invalid-certs
"""

[tasks.k8s_delete_kwok]
description = "Delete KWOK cluster"
run = """
kwokctl delete cluster --name="$CLUSTER_NAME"
"""
